
[window]
opacity = 0.85
padding = { x = 2, y = 2 }

[font]
size = 11.0

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

